make:
	streamlit run /Users/julian/Documents/ohio-u/senior-1/databases/FinalProject/Databases-Final-Project/streamlit/streamlit_test.py
make e:
	streamlit run /Users/esandstrom/Desktop/OU/FALL_23_S/cs_4620_DB/Databases-Final-Project/streamlit/streamlit_test.py
